version: '3.9'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - my_mongo:/data/db
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongodb
    command: >
      sh -c "python3 -m flask run --host=0.0.0.0 --port=8080"
volumes:
  my_mongo: